name: pokrov_linux_shell
description: Conditional Linux beta host for the POKROV client program.
publish_to: none
version: 1.2.0+30

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pokrov_app_shell:
    path: ../../packages/app_shell
  pokrov_core_domain:
    path: ../../packages/core_domain

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
