import android.app.UiAutomation;
import android.os.HandlerThread;
import android.accessibilityservice.AccessibilityServiceInfo;
import android.view.accessibility.AccessibilityNodeInfo;
import android.graphics.Rect;
public final class UiTreeProbe {
 static String xml(CharSequence s){if(s==null)return "";return s.toString().replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("\n","&#10;");}
 static void node(AccessibilityNodeInfo n,StringBuilder b){if(n==null)return;Rect r=new Rect();n.getBoundsInScreen(r);b.append("<node text=\"").append(xml(n.getText())).append("\" content-desc=\"").append(xml(n.getContentDescription())).append("\" package=\"").append(xml(n.getPackageName())).append("\" clickable=\"").append(n.isClickable()).append("\" scrollable=\"").append(n.isScrollable()).append("\" bounds=\"[").append(r.left).append(',').append(r.top).append("][").append(r.right).append(',').append(r.bottom).append("]\">");for(int i=0;i<n.getChildCount();i++)node(n.getChild(i),b);b.append("</node>");}
 public static void main(String[] a)throws Exception{HandlerThread t=new HandlerThread("pokrov-ui-observer");t.start();Class<?> bridge=Class.forName("android.app.UiAutomationConnection");Object c=bridge.getConstructor().newInstance();UiAutomation u=(UiAutomation)UiAutomation.class.getConstructor(android.os.Looper.class,Class.forName("android.app.IUiAutomationConnection")).newInstance(t.getLooper(),c);try{UiAutomation.class.getMethod("connect").invoke(u);AccessibilityServiceInfo info=u.getServiceInfo();info.flags|=AccessibilityServiceInfo.FLAG_RETRIEVE_INTERACTIVE_WINDOWS;u.setServiceInfo(info);AccessibilityNodeInfo root=null;for(int attempt=0;attempt<30&&root==null;attempt++){Thread.sleep(100);root=u.getRootInActiveWindow();}if(root==null)throw new IllegalStateException("no active root");StringBuilder b=new StringBuilder("<?xml version=\"1.0\"?><hierarchy>");node(root,b);System.out.println(b.append("</hierarchy>"));}finally{UiAutomation.class.getMethod("disconnect").invoke(u);t.quitSafely();}}
}
