from pathlib import Path
import json,hashlib,subprocess
out=Path('E:/r12-c05-android-cronet');root=Path('E:/r12client');sha=lambda b:hashlib.sha256(b).hexdigest();r=json.loads((out/'notice-inputs.json').read_text());data=bytearray(b'POKROV Android Cronet third-party notices\n\nNative source: SagerNet/naiveproxy 30f3a5689ac20ba1b87c1ce58f66d3aaa8b2cfe5\nChromium 143.0.7499.109; Android static Cronet dependency inputs.\nThe sections include source-project licenses and supporting attributions.\n\n');sections=[]
for s in r['sections']:
 b=Path(s['body_file']).read_bytes();assert sha(b)==s['sha256'];data.extend(('\n'+'='*78+'\n'+s['name']+'\nSource: '+s['origin']+'\n'+'='*78+'\n\n').encode());offset=len(data);data.extend(b);data.extend(b'\n');sections.append({**s,'body_offset':offset})
asset=root/'apps/android_shell/assets/licenses/cronet-NOTICES.txt';assert not asset.exists();asset.write_bytes(data);report={'schema':'pokrov.android-cronet-notices/v1','client_before':subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip(),'native_source_commit':r['native_commit'],'core_source_commit':'8dc57a830bd1487389dd1b7c9190f094c31e13bc','asset':{'path':asset.relative_to(root).as_posix(),'bytes':len(data),'sha256':sha(data)},'sections':sections,'scope':r['scope'],'full_license_clearance':False};(out/'assembly.json').write_text(json.dumps(report,indent=2)+'\n');print(len(sections),report['asset'])
# A source-bound supplement; static archive inputs are not final delivered libraries.
rows=json.loads((out/'source-object-mapping.json').read_text());libs=json.loads(Path('E:/r12-c05-source-packet/android-cronet-library-binding.json').read_text());directories=sorted(set(n.split('third_party/',1)[0]+'third_party/'+n.split('third_party/',1)[1].split('/')[0] for row in rows for t in row['targets'] for n in t.get('sources',[]) if 'third_party/' in n and not n.startswith('//out/')));metadata={m['source_directory']:m for m in r['source_readmes']};comps=[];deps=[]
for directory in directories:
 rel=directory.removeprefix('//');ref='naive:'+r['native_commit']+':'+rel;md=metadata.get(rel);props=[{'name':'pokrov:source-directory','value':rel},{'name':'pokrov:evidence-scope','value':'GN-declared native source input; version below identifies the containing source snapshot, not the upstream package release.'}]
 if md:props.append({'name':'pokrov:readme-chromium-sha256','value':md['readme_sha256']})
 comps.append({'type':'library','name':rel,'version':r['native_commit'],'bom-ref':ref,'externalReferences':[{'type':'vcs','url':'https://github.com/SagerNet/naiveproxy/tree/'+r['native_commit']+'/src/'+rel}],'properties':props})
for lib in libs:
 ref='cronet-static:'+lib['arch'];archrow=next(row for row in rows if row['goarch']==lib['arch']);included=sorted(set(n.split('third_party/',1)[0]+'third_party/'+n.split('third_party/',1)[1].split('/')[0] for t in archrow['targets'] for n in t.get('sources',[]) if 'third_party/' in n and not n.startswith('//out/')));comps.append({'type':'library','name':'libcronet.a','version':'143.0.7499.109/android-'+lib['arch'],'bom-ref':ref,'hashes':[{'alg':'SHA-256','content':lib['sha256']}],'properties':[{'name':'pokrov:evidence-scope','value':'Pinned static link input. Android 386 is in the AAR but not the current APKs; others contribute to bound Core SOs. Object/source filename multiset congruence does not establish full binary reproduction.'}]});deps.append({'ref':ref,'dependsOn':['naive:'+r['native_commit']+':'+d.removeprefix('//') for d in included]})
bom={'bomFormat':'CycloneDX','specVersion':'1.6','version':1,'metadata':{'component':{'type':'application','name':'POKROV Android Cronet native input supplement','version':'1.2.0+4053','bom-ref':'pokrov-android-cronet-inputs'}},'components':comps,'dependencies':[{'ref':'pokrov-android-cronet-inputs','dependsOn':['cronet-static:'+lib['arch'] for lib in libs]}]+deps};(out/'cronet-supplement.cdx.json').write_text(json.dumps(bom,indent=2)+'\n');print('SBOM',len(comps),'source directories',len(directories))
